### ISSUE TITLE
Latest crash on 1.8.9 due to Gson JsonArray.add(String) doesn't exist

### ISSUE THREAD

**Issue by HowardZHY** [Ecdcaeb/Redirector#16]
https://github.com/Ecdcaeb/Redirector/commit/f10eeea4ec5fe91c2205fcad216f28e909c2e82a#diff-aab09adf90f1431b3d6cbe9f4c1500324e4545694c0fd1b0093495ab05b3c157R60

```[18:17:12] [main/WARN] [FML/]: The coremod com.Hileb.teampotato.redirectionor.Redirectionor does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:17:12] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
[18:17:12] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at com.Hileb.teampotato.redirectionor.RedirectionorConfig.encode(RedirectionorConfig.java:74)
[18:17:12] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at com.Hileb.teampotato.redirectionor.RedirectionorConfig.save(RedirectionorConfig.java:91)
[18:17:12] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at com.Hileb.teampotato.redirectionor.RedirectionorConfig.initConfig(RedirectionorConfig.java:114)
[18:17:12] [main/INFO] [STDERR/]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:99]: 	at com.Hileb.teampotato.redirectionor.Redirectionor.<init>(Redirectionor.java:17)```

**Comment by Ecdcaeb** [comment]
https://github.com/google/gson/commit/6960ebc77684dd07125e39caefc140262b1fb76e

**Comment by Ecdcaeb** [comment]
https://github.com/MCTeamPotato/Redirector/commit/b0ad434af1ffb0846ec7c478b9fd6d1c61ee792e
