### ISSUE TITLE
Conflict with Custom Skin Loader

### ISSUE THREAD

**Issue by HowardZHY** [Ecdcaeb/Redirector#8]
[14:49:45] [Herobrine's skull/INFO] [STDOUT/]: [com.Hileb.teampotato.redirectionor.RedirectionorTansformer:transform:53]: Redirect customskinloader.utils.TextureUtil$AuthlibField
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: java.lang.NoSuchMethodError: customskinloader.fake.FakeSkinManager.createThreadDownloadImageData(Lcom/google/common/collect/ImmutableList;Lcom/mojang/authlib/minecraft/MinecraftProfileTexture;Lcom/mojang/authlib/minecraft/MinecraftProfileTexture$Type;Lnet/minecraft/client/resources/SkinManager$SkinAvailableCallback;)[Ljava/lang/Object;
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.resources.SkinManager.loadSkin(SourceFile:68)
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.resources.SkinManager.loadSkin(SourceFile:53)
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.renderer.tileentity.TileEntitySkullRenderer.renderSkull(SourceFile:78)
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.renderByItem(TileEntityItemStackRenderer.java:64)
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.renderer.entity.RenderItem.renderItem(RenderItem.java:196)
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:533)
[14:49:45] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.renderer.entity.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:575)

**Comment by HowardZHY** [comment]
CSL latest version's bug
